apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
  labels:
    app: secure-app
spec:
  containers:
  - name: secure-container
    image: nginx:1.21
    securityContext:
      runAsUser: 1000               # Run as a non-root user with UID 1000
      runAsGroup: 3000              # Run with a non-root group with GID 3000
      runAsNonRoot: true            # Ensure the container does not run as root
      allowPrivilegeEscalation: false # Prevent privilege escalation
      capabilities:
        drop:
        - ALL                       # Drop all Linux capabilities
      readOnlyRootFilesystem: true  # Set the root filesystem to read-only
    ports:
    - containerPort: 80
  securityContext:
    fsGroup: 2000                   # Set the group ID for mounted volumes to 2000

